[dataset_specific]
description = "variables affecting how the final HTML report appears"
seqr_lookup = ""
external_lookup = ""
seqr_instance = "https://this.is.a/placeholder"
seqr_project = "placeholder"
forbidden = ""