[buckets]
web_suffix = "web"
tmp_suffix = "tmp"
analysis_suffix = "analysis"

[workflow]
name = "AIP"
scatter_count = 50

[moi_tests]
description = "thresholds for different filters during the MOI checks"
gnomad_dominant = 0.001
gnomad_max_homs_dominant = 1
gnomad_max_homs_recessive = 2
gnomad_max_ac_dominant = 50
gnomad_max_hemi = 2

[csq]
description = "variables affecting how the VCF variants are parsed, and AnalysisVariant objects are populated"
csq_string = [ "allele", "consequence", "symbol", "gene", "feature", "mane_select", "biotype", "exon", "hgvsc", "hgvsp", "cdna_position", "cds_position", "protein_position", "amino_acids", "codons", "allele_num", "variant_class", "tsl", "appris", "ccds", "ensp", "swissprot", "trembl", "uniparc", "gene_pheno", "sift", "polyphen", "lof", "lof_filter", "lof_flags",]

[filter]
description = "variables for the hail operations, including CSQ sets and filter thresholds"
ac_threshold = 0.01
additional_csq = [ "missense_variant"]
af_semi_rare = 0.01
cadd = 28.1
critical_csq = [ "frameshift_variant", "splice_acceptor_variant", "splice_donor_variant", "start_lost", "stop_gained", "stop_lost", "transcript_ablation",]
gerp = 1.0
eigen = 0.25
polyphen = 0.99
revel = 0.77
sift = 0.0
spliceai = 0.5

[hail]
cancel_after_n_failures = 1
default_timeout = 6000
default_memory = "highmem"
