[dataset_specific]
description = "variables affecting how the final HTML report appears"
external_lookup = "hail-az://raregen001sa/test/inputs/rgp/rgp_seqr_id_mapping.json"
forbidden = "hail-az://raregen001sa/test/inputs/rgp/forbidden-empty.json"

seqr_instance = "http://seqr.broadinstitute.org/"
seqr_project = "R0384_rare_genomes_project_gen"
seqr_lookup = "hail-az://raregen001sa/test/inputs/rgp/rgp_seqr_id_mapping.json"